add support for adding relative URLs to the index.
hypnoglow/helm-s3 pull request #122
Opened 2020-09-25 15:26 UTC by bashims

Signed-off-by: Benjamin Ash <bash@intelerad.com>

2020-10-20 17:02 UTC, bashims commented
@hypnoglow any chance you could look at this PR?

Thanks!

2020-10-23 17:55 UTC, davidkarlsen commented
I think this is an elegant solution which obsoletes https://github.com/hypnoglow/helm-s3/pull/56

2020-10-23 21:17 UTC, davidkarlsen commented
@bashims this repo seems dead - how can one apply your PR and run with that version in helm?

2020-10-23 22:13 UTC, bashims commented
@davidkarlsen yeah not entirely sure what is going on here. You can install from my forked release if you want - I tagged it as v0.9.3

Installation instructions:

`helm plugin install https://github.com/bashims/helm-s3.git --version 0.9.3`

2020-10-24 18:44 UTC, hypnoglow requested changes
Thanks a lot for this contribution!

Overall looks fine, a few nits on test changes.

2020-10-24 18:44 UTC, hypnoglow commented on hack/integration-tests-local.sh
> +  if $(docker container ls | grep -q "${DOCKER_NAME}\$") ; then
We should omit `$()` here:

```suggestion
  if docker container ls | grep -q "${DOCKER_NAME}$" ; then
```

2020-10-24 18:44 UTC, hypnoglow commented on hack/integration-tests-local.sh
> +sleep 3
Could you add a comment why we need to sleep here?

2020-10-24 18:44 UTC, hypnoglow commented on hack/integration-tests-local.sh
> +  if [ -z "${SKIP_CLEANUP}" ]; then
This test now fails without this variable set: 

```
./hack/integration-tests-local.sh: line 26: SKIP_CLEANUP: unbound variable
```

```suggestion
  if [ -z "${SKIP_CLEANUP:-}" ]; then
```

2020-10-24 18:44 UTC, hypnoglow commented on hack/integration-tests-local.sh
> +    docker container rm --force --volumes "${DOCKER_NAME}" || :
```suggestion
    docker container rm --force --volumes "${DOCKER_NAME}" &>/dev/null || :
```

2020-10-24 18:44 UTC, hypnoglow commented on hack/integration-tests-local.sh
> +docker container run -d --rm --name helm-s3-minio \
```suggestion
docker container run -d --rm --name "${DOCKER_NAME}" \
```

2020-10-24 18:44 UTC, hypnoglow commented on tests/e2e/push_test.go
> +	cmd, stdout, stderr = command(fmt.Sprintf("helm fetch %s/%s --version %s", name, chartName, chartVer))
`os.Chdir` can cause problems.

Could you please either add `--destination` flag to helm command or use something like

```
	wd, _ := os.Getwd()
	os.Chdir(tmpdir)
	defer os.Chdir(wd)
```

2020-10-24 18:44 UTC, hypnoglow commented
Tested it locally, works fine, thanks.

2020-10-26 14:15 UTC, bashims commented on hack/integration-tests-local.sh
> +set -x -e -uo pipefail
fixed

2020-10-26 14:15 UTC, bashims commented on hack/integration-tests-local.sh
> +  if $(docker container ls | grep -q "${DOCKER_NAME}\$") ; then
fixed

2020-10-26 18:14 UTC, hypnoglow commented
@bashims I don't see any changes in the code. Have you pushed them?

2020-10-26 18:31 UTC, bashims commented
@hypnoglow just pushed

2020-10-26 19:00 UTC, merged

2020-10-26 19:00 UTC, hypnoglow commented
Thank you!